// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpatialParquet.proto

package gr.ds.unipi.spatialnodb.messages.proto.spatialparquet;

/**
 * Protobuf type {@code Geometry}
 */
public  final class Geometry extends
    com.google.protobuf.GeneratedMessage
    implements GeometryOrBuilder {
  // Use Geometry.newBuilder() to construct.
  private Geometry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Geometry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Geometry defaultInstance;
  public static Geometry getDefaultInstance() {
    return defaultInstance;
  }

  public Geometry getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Geometry(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            geometry_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              part_ = new java.util.ArrayList<gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part>();
              mutable_bitField0_ |= 0x00000002;
            }
            part_.add(input.readMessage(gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        part_ = java.util.Collections.unmodifiableList(part_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.SpatialParquetProtos.internal_static_Geometry_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.SpatialParquetProtos.internal_static_Geometry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.class, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Builder.class);
  }

  public static com.google.protobuf.Parser<Geometry> PARSER =
      new com.google.protobuf.AbstractParser<Geometry>() {
    public Geometry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Geometry(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Geometry> getParserForType() {
    return PARSER;
  }

  public interface PartOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Geometry.Part.Coordinate coordinate = 1;
    /**
     * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
     */
    java.util.List<gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate>
        getCoordinateList();
    /**
     * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
     */
    gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate getCoordinate(int index);
    /**
     * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
     */
    int getCoordinateCount();
    /**
     * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
     */
    java.util.List<? extends gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.CoordinateOrBuilder>
        getCoordinateOrBuilderList();
    /**
     * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
     */
    gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.CoordinateOrBuilder getCoordinateOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Geometry.Part}
   */
  public static final class Part extends
      com.google.protobuf.GeneratedMessage
      implements PartOrBuilder {
    // Use Part.newBuilder() to construct.
    private Part(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Part(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Part defaultInstance;
    public static Part getDefaultInstance() {
      return defaultInstance;
    }

    public Part getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Part(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                coordinate_ = new java.util.ArrayList<gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate>();
                mutable_bitField0_ |= 0x00000001;
              }
              coordinate_.add(input.readMessage(gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          coordinate_ = java.util.Collections.unmodifiableList(coordinate_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.SpatialParquetProtos.internal_static_Geometry_Part_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.SpatialParquetProtos.internal_static_Geometry_Part_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.class, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Builder.class);
    }

    public static com.google.protobuf.Parser<Part> PARSER =
        new com.google.protobuf.AbstractParser<Part>() {
      public Part parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Part(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Part> getParserForType() {
      return PARSER;
    }

    public interface CoordinateOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required double x = 1;
      /**
       * <code>required double x = 1;</code>
       */
      boolean hasX();
      /**
       * <code>required double x = 1;</code>
       */
      double getX();

      // required double y = 2;
      /**
       * <code>required double y = 2;</code>
       */
      boolean hasY();
      /**
       * <code>required double y = 2;</code>
       */
      double getY();
    }
    /**
     * Protobuf type {@code Geometry.Part.Coordinate}
     */
    public static final class Coordinate extends
        com.google.protobuf.GeneratedMessage
        implements CoordinateOrBuilder {
      // Use Coordinate.newBuilder() to construct.
      private Coordinate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Coordinate(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Coordinate defaultInstance;
      public static Coordinate getDefaultInstance() {
        return defaultInstance;
      }

      public Coordinate getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Coordinate(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 9: {
                bitField0_ |= 0x00000001;
                x_ = input.readDouble();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                y_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.SpatialParquetProtos.internal_static_Geometry_Part_Coordinate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.SpatialParquetProtos.internal_static_Geometry_Part_Coordinate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.class, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.Builder.class);
      }

      public static com.google.protobuf.Parser<Coordinate> PARSER =
          new com.google.protobuf.AbstractParser<Coordinate>() {
        public Coordinate parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Coordinate(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Coordinate> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required double x = 1;
      public static final int X_FIELD_NUMBER = 1;
      private double x_;
      /**
       * <code>required double x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double x = 1;</code>
       */
      public double getX() {
        return x_;
      }

      // required double y = 2;
      public static final int Y_FIELD_NUMBER = 2;
      private double y_;
      /**
       * <code>required double y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double y = 2;</code>
       */
      public double getY() {
        return y_;
      }

      private void initFields() {
        x_ = 0D;
        y_ = 0D;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasX()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasY()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeDouble(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, y_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, y_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate)) {
          return super.equals(obj);
        }
        gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate other = (gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate) obj;

        boolean result = true;
        result = result && (hasX() == other.hasX());
        if (hasX()) {
          result = result && (Double.doubleToLongBits(getX())    == Double.doubleToLongBits(other.getX()));
        }
        result = result && (hasY() == other.hasY());
        if (hasY()) {
          result = result && (Double.doubleToLongBits(getY())    == Double.doubleToLongBits(other.getY()));
        }
        result = result &&
            getUnknownFields().equals(other.getUnknownFields());
        return result;
      }

      private int memoizedHashCode = 0;
      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        if (hasX()) {
          hash = (37 * hash) + X_FIELD_NUMBER;
          hash = (53 * hash) + hashLong(
              Double.doubleToLongBits(getX()));
        }
        if (hasY()) {
          hash = (37 * hash) + Y_FIELD_NUMBER;
          hash = (53 * hash) + hashLong(
              Double.doubleToLongBits(getY()));
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Geometry.Part.Coordinate}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.CoordinateOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.SpatialParquetProtos.internal_static_Geometry_Part_Coordinate_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.SpatialParquetProtos.internal_static_Geometry_Part_Coordinate_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.class, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.Builder.class);
        }

        // Construct using gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          x_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000001);
          y_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.SpatialParquetProtos.internal_static_Geometry_Part_Coordinate_descriptor;
        }

        public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate getDefaultInstanceForType() {
          return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.getDefaultInstance();
        }

        public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate build() {
          gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate buildPartial() {
          gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate result = new gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.x_ = x_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.y_ = y_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate) {
            return mergeFrom((gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate other) {
          if (other == gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.getDefaultInstance()) return this;
          if (other.hasX()) {
            setX(other.getX());
          }
          if (other.hasY()) {
            setY(other.getY());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasX()) {
            
            return false;
          }
          if (!hasY()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required double x = 1;
        private double x_ ;
        /**
         * <code>required double x = 1;</code>
         */
        public boolean hasX() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required double x = 1;</code>
         */
        public double getX() {
          return x_;
        }
        /**
         * <code>required double x = 1;</code>
         */
        public Builder setX(double value) {
          bitField0_ |= 0x00000001;
          x_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double x = 1;</code>
         */
        public Builder clearX() {
          bitField0_ = (bitField0_ & ~0x00000001);
          x_ = 0D;
          onChanged();
          return this;
        }

        // required double y = 2;
        private double y_ ;
        /**
         * <code>required double y = 2;</code>
         */
        public boolean hasY() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required double y = 2;</code>
         */
        public double getY() {
          return y_;
        }
        /**
         * <code>required double y = 2;</code>
         */
        public Builder setY(double value) {
          bitField0_ |= 0x00000002;
          y_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double y = 2;</code>
         */
        public Builder clearY() {
          bitField0_ = (bitField0_ & ~0x00000002);
          y_ = 0D;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Geometry.Part.Coordinate)
      }

      static {
        defaultInstance = new Coordinate(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Geometry.Part.Coordinate)
    }

    // repeated .Geometry.Part.Coordinate coordinate = 1;
    public static final int COORDINATE_FIELD_NUMBER = 1;
    private java.util.List<gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate> coordinate_;
    /**
     * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
     */
    public java.util.List<gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate> getCoordinateList() {
      return coordinate_;
    }
    /**
     * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
     */
    public java.util.List<? extends gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.CoordinateOrBuilder>
        getCoordinateOrBuilderList() {
      return coordinate_;
    }
    /**
     * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
     */
    public int getCoordinateCount() {
      return coordinate_.size();
    }
    /**
     * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
     */
    public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate getCoordinate(int index) {
      return coordinate_.get(index);
    }
    /**
     * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
     */
    public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.CoordinateOrBuilder getCoordinateOrBuilder(
        int index) {
      return coordinate_.get(index);
    }

    private void initFields() {
      coordinate_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getCoordinateCount(); i++) {
        if (!getCoordinate(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < coordinate_.size(); i++) {
        output.writeMessage(1, coordinate_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < coordinate_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, coordinate_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part)) {
        return super.equals(obj);
      }
      gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part other = (gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part) obj;

      boolean result = true;
      result = result && getCoordinateList()
          .equals(other.getCoordinateList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getCoordinateCount() > 0) {
        hash = (37 * hash) + COORDINATE_FIELD_NUMBER;
        hash = (53 * hash) + getCoordinateList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Geometry.Part}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.PartOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.SpatialParquetProtos.internal_static_Geometry_Part_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.SpatialParquetProtos.internal_static_Geometry_Part_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.class, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Builder.class);
      }

      // Construct using gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCoordinateFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (coordinateBuilder_ == null) {
          coordinate_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          coordinateBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.SpatialParquetProtos.internal_static_Geometry_Part_descriptor;
      }

      public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part getDefaultInstanceForType() {
        return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.getDefaultInstance();
      }

      public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part build() {
        gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part buildPartial() {
        gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part result = new gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part(this);
        int from_bitField0_ = bitField0_;
        if (coordinateBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            coordinate_ = java.util.Collections.unmodifiableList(coordinate_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.coordinate_ = coordinate_;
        } else {
          result.coordinate_ = coordinateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part) {
          return mergeFrom((gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part other) {
        if (other == gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.getDefaultInstance()) return this;
        if (coordinateBuilder_ == null) {
          if (!other.coordinate_.isEmpty()) {
            if (coordinate_.isEmpty()) {
              coordinate_ = other.coordinate_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCoordinateIsMutable();
              coordinate_.addAll(other.coordinate_);
            }
            onChanged();
          }
        } else {
          if (!other.coordinate_.isEmpty()) {
            if (coordinateBuilder_.isEmpty()) {
              coordinateBuilder_.dispose();
              coordinateBuilder_ = null;
              coordinate_ = other.coordinate_;
              bitField0_ = (bitField0_ & ~0x00000001);
              coordinateBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCoordinateFieldBuilder() : null;
            } else {
              coordinateBuilder_.addAllMessages(other.coordinate_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getCoordinateCount(); i++) {
          if (!getCoordinate(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Geometry.Part.Coordinate coordinate = 1;
      private java.util.List<gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate> coordinate_ =
        java.util.Collections.emptyList();
      private void ensureCoordinateIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          coordinate_ = new java.util.ArrayList<gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate>(coordinate_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.Builder, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.CoordinateOrBuilder> coordinateBuilder_;

      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public java.util.List<gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate> getCoordinateList() {
        if (coordinateBuilder_ == null) {
          return java.util.Collections.unmodifiableList(coordinate_);
        } else {
          return coordinateBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public int getCoordinateCount() {
        if (coordinateBuilder_ == null) {
          return coordinate_.size();
        } else {
          return coordinateBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate getCoordinate(int index) {
        if (coordinateBuilder_ == null) {
          return coordinate_.get(index);
        } else {
          return coordinateBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public Builder setCoordinate(
          int index, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate value) {
        if (coordinateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoordinateIsMutable();
          coordinate_.set(index, value);
          onChanged();
        } else {
          coordinateBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public Builder setCoordinate(
          int index, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.Builder builderForValue) {
        if (coordinateBuilder_ == null) {
          ensureCoordinateIsMutable();
          coordinate_.set(index, builderForValue.build());
          onChanged();
        } else {
          coordinateBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public Builder addCoordinate(gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate value) {
        if (coordinateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoordinateIsMutable();
          coordinate_.add(value);
          onChanged();
        } else {
          coordinateBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public Builder addCoordinate(
          int index, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate value) {
        if (coordinateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoordinateIsMutable();
          coordinate_.add(index, value);
          onChanged();
        } else {
          coordinateBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public Builder addCoordinate(
          gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.Builder builderForValue) {
        if (coordinateBuilder_ == null) {
          ensureCoordinateIsMutable();
          coordinate_.add(builderForValue.build());
          onChanged();
        } else {
          coordinateBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public Builder addCoordinate(
          int index, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.Builder builderForValue) {
        if (coordinateBuilder_ == null) {
          ensureCoordinateIsMutable();
          coordinate_.add(index, builderForValue.build());
          onChanged();
        } else {
          coordinateBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public Builder addAllCoordinate(
          java.lang.Iterable<? extends gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate> values) {
        if (coordinateBuilder_ == null) {
          ensureCoordinateIsMutable();
          super.addAll(values, coordinate_);
          onChanged();
        } else {
          coordinateBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public Builder clearCoordinate() {
        if (coordinateBuilder_ == null) {
          coordinate_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          coordinateBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public Builder removeCoordinate(int index) {
        if (coordinateBuilder_ == null) {
          ensureCoordinateIsMutable();
          coordinate_.remove(index);
          onChanged();
        } else {
          coordinateBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.Builder getCoordinateBuilder(
          int index) {
        return getCoordinateFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.CoordinateOrBuilder getCoordinateOrBuilder(
          int index) {
        if (coordinateBuilder_ == null) {
          return coordinate_.get(index);  } else {
          return coordinateBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public java.util.List<? extends gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.CoordinateOrBuilder>
           getCoordinateOrBuilderList() {
        if (coordinateBuilder_ != null) {
          return coordinateBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(coordinate_);
        }
      }
      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.Builder addCoordinateBuilder() {
        return getCoordinateFieldBuilder().addBuilder(
            gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.getDefaultInstance());
      }
      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.Builder addCoordinateBuilder(
          int index) {
        return getCoordinateFieldBuilder().addBuilder(
            index, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.getDefaultInstance());
      }
      /**
       * <code>repeated .Geometry.Part.Coordinate coordinate = 1;</code>
       */
      public java.util.List<gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.Builder>
           getCoordinateBuilderList() {
        return getCoordinateFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.Builder, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.CoordinateOrBuilder>
          getCoordinateFieldBuilder() {
        if (coordinateBuilder_ == null) {
          coordinateBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Coordinate.Builder, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.CoordinateOrBuilder>(
                  coordinate_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          coordinate_ = null;
        }
        return coordinateBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Geometry.Part)
    }

    static {
      defaultInstance = new Part(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Geometry.Part)
  }

  private int bitField0_;
  // required int32 geometry = 1;
  public static final int GEOMETRY_FIELD_NUMBER = 1;
  private int geometry_;
  /**
   * <code>required int32 geometry = 1;</code>
   */
  public boolean hasGeometry() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int32 geometry = 1;</code>
   */
  public int getGeometry() {
    return geometry_;
  }

  // repeated .Geometry.Part part = 2;
  public static final int PART_FIELD_NUMBER = 2;
  private java.util.List<gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part> part_;
  /**
   * <code>repeated .Geometry.Part part = 2;</code>
   */
  public java.util.List<gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part> getPartList() {
    return part_;
  }
  /**
   * <code>repeated .Geometry.Part part = 2;</code>
   */
  public java.util.List<? extends gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.PartOrBuilder>
      getPartOrBuilderList() {
    return part_;
  }
  /**
   * <code>repeated .Geometry.Part part = 2;</code>
   */
  public int getPartCount() {
    return part_.size();
  }
  /**
   * <code>repeated .Geometry.Part part = 2;</code>
   */
  public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part getPart(int index) {
    return part_.get(index);
  }
  /**
   * <code>repeated .Geometry.Part part = 2;</code>
   */
  public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.PartOrBuilder getPartOrBuilder(
      int index) {
    return part_.get(index);
  }

  private void initFields() {
    geometry_ = 0;
    part_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasGeometry()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getPartCount(); i++) {
      if (!getPart(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, geometry_);
    }
    for (int i = 0; i < part_.size(); i++) {
      output.writeMessage(2, part_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, geometry_);
    }
    for (int i = 0; i < part_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, part_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry)) {
      return super.equals(obj);
    }
    gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry other = (gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry) obj;

    boolean result = true;
    result = result && (hasGeometry() == other.hasGeometry());
    if (hasGeometry()) {
      result = result && (getGeometry()
          == other.getGeometry());
    }
    result = result && getPartList()
        .equals(other.getPartList());
    result = result &&
        getUnknownFields().equals(other.getUnknownFields());
    return result;
  }

  private int memoizedHashCode = 0;
  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasGeometry()) {
      hash = (37 * hash) + GEOMETRY_FIELD_NUMBER;
      hash = (53 * hash) + getGeometry();
    }
    if (getPartCount() > 0) {
      hash = (37 * hash) + PART_FIELD_NUMBER;
      hash = (53 * hash) + getPartList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Geometry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.GeometryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.SpatialParquetProtos.internal_static_Geometry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.SpatialParquetProtos.internal_static_Geometry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.class, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Builder.class);
    }

    // Construct using gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getPartFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      geometry_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (partBuilder_ == null) {
        part_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        partBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.SpatialParquetProtos.internal_static_Geometry_descriptor;
    }

    public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry getDefaultInstanceForType() {
      return gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.getDefaultInstance();
    }

    public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry build() {
      gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry buildPartial() {
      gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry result = new gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.geometry_ = geometry_;
      if (partBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          part_ = java.util.Collections.unmodifiableList(part_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.part_ = part_;
      } else {
        result.part_ = partBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry) {
        return mergeFrom((gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry other) {
      if (other == gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.getDefaultInstance()) return this;
      if (other.hasGeometry()) {
        setGeometry(other.getGeometry());
      }
      if (partBuilder_ == null) {
        if (!other.part_.isEmpty()) {
          if (part_.isEmpty()) {
            part_ = other.part_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePartIsMutable();
            part_.addAll(other.part_);
          }
          onChanged();
        }
      } else {
        if (!other.part_.isEmpty()) {
          if (partBuilder_.isEmpty()) {
            partBuilder_.dispose();
            partBuilder_ = null;
            part_ = other.part_;
            bitField0_ = (bitField0_ & ~0x00000002);
            partBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getPartFieldBuilder() : null;
          } else {
            partBuilder_.addAllMessages(other.part_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasGeometry()) {
        
        return false;
      }
      for (int i = 0; i < getPartCount(); i++) {
        if (!getPart(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required int32 geometry = 1;
    private int geometry_ ;
    /**
     * <code>required int32 geometry = 1;</code>
     */
    public boolean hasGeometry() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 geometry = 1;</code>
     */
    public int getGeometry() {
      return geometry_;
    }
    /**
     * <code>required int32 geometry = 1;</code>
     */
    public Builder setGeometry(int value) {
      bitField0_ |= 0x00000001;
      geometry_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 geometry = 1;</code>
     */
    public Builder clearGeometry() {
      bitField0_ = (bitField0_ & ~0x00000001);
      geometry_ = 0;
      onChanged();
      return this;
    }

    // repeated .Geometry.Part part = 2;
    private java.util.List<gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part> part_ =
      java.util.Collections.emptyList();
    private void ensurePartIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        part_ = new java.util.ArrayList<gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part>(part_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Builder, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.PartOrBuilder> partBuilder_;

    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public java.util.List<gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part> getPartList() {
      if (partBuilder_ == null) {
        return java.util.Collections.unmodifiableList(part_);
      } else {
        return partBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public int getPartCount() {
      if (partBuilder_ == null) {
        return part_.size();
      } else {
        return partBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part getPart(int index) {
      if (partBuilder_ == null) {
        return part_.get(index);
      } else {
        return partBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public Builder setPart(
        int index, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part value) {
      if (partBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartIsMutable();
        part_.set(index, value);
        onChanged();
      } else {
        partBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public Builder setPart(
        int index, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Builder builderForValue) {
      if (partBuilder_ == null) {
        ensurePartIsMutable();
        part_.set(index, builderForValue.build());
        onChanged();
      } else {
        partBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public Builder addPart(gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part value) {
      if (partBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartIsMutable();
        part_.add(value);
        onChanged();
      } else {
        partBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public Builder addPart(
        int index, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part value) {
      if (partBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartIsMutable();
        part_.add(index, value);
        onChanged();
      } else {
        partBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public Builder addPart(
        gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Builder builderForValue) {
      if (partBuilder_ == null) {
        ensurePartIsMutable();
        part_.add(builderForValue.build());
        onChanged();
      } else {
        partBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public Builder addPart(
        int index, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Builder builderForValue) {
      if (partBuilder_ == null) {
        ensurePartIsMutable();
        part_.add(index, builderForValue.build());
        onChanged();
      } else {
        partBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public Builder addAllPart(
        java.lang.Iterable<? extends gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part> values) {
      if (partBuilder_ == null) {
        ensurePartIsMutable();
        super.addAll(values, part_);
        onChanged();
      } else {
        partBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public Builder clearPart() {
      if (partBuilder_ == null) {
        part_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        partBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public Builder removePart(int index) {
      if (partBuilder_ == null) {
        ensurePartIsMutable();
        part_.remove(index);
        onChanged();
      } else {
        partBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Builder getPartBuilder(
        int index) {
      return getPartFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.PartOrBuilder getPartOrBuilder(
        int index) {
      if (partBuilder_ == null) {
        return part_.get(index);  } else {
        return partBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public java.util.List<? extends gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.PartOrBuilder>
         getPartOrBuilderList() {
      if (partBuilder_ != null) {
        return partBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(part_);
      }
    }
    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Builder addPartBuilder() {
      return getPartFieldBuilder().addBuilder(
          gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.getDefaultInstance());
    }
    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Builder addPartBuilder(
        int index) {
      return getPartFieldBuilder().addBuilder(
          index, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.getDefaultInstance());
    }
    /**
     * <code>repeated .Geometry.Part part = 2;</code>
     */
    public java.util.List<gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Builder>
         getPartBuilderList() {
      return getPartFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Builder, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.PartOrBuilder>
        getPartFieldBuilder() {
      if (partBuilder_ == null) {
        partBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part.Builder, gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.PartOrBuilder>(
                part_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        part_ = null;
      }
      return partBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Geometry)
  }

  static {
    defaultInstance = new Geometry(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:Geometry)
}

