// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpatialParquet.proto

package gr.ds.unipi.spatialnodb.messages.proto.spatialparquet;

public interface GeometryOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required int32 geometry = 1;
  /**
   * <code>required int32 geometry = 1;</code>
   */
  boolean hasGeometry();
  /**
   * <code>required int32 geometry = 1;</code>
   */
  int getGeometry();

  // repeated .Geometry.Part part = 2;
  /**
   * <code>repeated .Geometry.Part part = 2;</code>
   */
  java.util.List<gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part>
      getPartList();
  /**
   * <code>repeated .Geometry.Part part = 2;</code>
   */
  gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.Part getPart(int index);
  /**
   * <code>repeated .Geometry.Part part = 2;</code>
   */
  int getPartCount();
  /**
   * <code>repeated .Geometry.Part part = 2;</code>
   */
  java.util.List<? extends gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.PartOrBuilder>
      getPartOrBuilderList();
  /**
   * <code>repeated .Geometry.Part part = 2;</code>
   */
  gr.ds.unipi.spatialnodb.messages.proto.spatialparquet.Geometry.PartOrBuilder getPartOrBuilder(
      int index);
}
