// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GeoParquet.proto

package gr.ds.unipi.spatialnodb.messages.proto.geoparquet;

/**
 * Protobuf type {@code Geometry}
 */
public  final class Geometry extends
    com.google.protobuf.GeneratedMessage
    implements GeometryOrBuilder {
  // Use Geometry.newBuilder() to construct.
  private Geometry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Geometry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Geometry defaultInstance;
  public static Geometry getDefaultInstance() {
    return defaultInstance;
  }

  public Geometry getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Geometry(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            geometry_ = input.readBytes();
            break;
          }
          case 17: {
            bitField0_ |= 0x00000002;
            minX_ = input.readDouble();
            break;
          }
          case 25: {
            bitField0_ |= 0x00000004;
            maxX_ = input.readDouble();
            break;
          }
          case 33: {
            bitField0_ |= 0x00000008;
            minY_ = input.readDouble();
            break;
          }
          case 41: {
            bitField0_ |= 0x00000010;
            maxY_ = input.readDouble();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gr.ds.unipi.spatialnodb.messages.proto.geoparquet.GeoParquetProtos.internal_static_Geometry_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gr.ds.unipi.spatialnodb.messages.proto.geoparquet.GeoParquetProtos.internal_static_Geometry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry.class, gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry.Builder.class);
  }

  public static com.google.protobuf.Parser<Geometry> PARSER =
      new com.google.protobuf.AbstractParser<Geometry>() {
    public Geometry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Geometry(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Geometry> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required bytes geometry = 1;
  public static final int GEOMETRY_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString geometry_;
  /**
   * <code>required bytes geometry = 1;</code>
   */
  public boolean hasGeometry() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required bytes geometry = 1;</code>
   */
  public com.google.protobuf.ByteString getGeometry() {
    return geometry_;
  }

  // required double minX = 2;
  public static final int MINX_FIELD_NUMBER = 2;
  private double minX_;
  /**
   * <code>required double minX = 2;</code>
   */
  public boolean hasMinX() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required double minX = 2;</code>
   */
  public double getMinX() {
    return minX_;
  }

  // required double maxX = 3;
  public static final int MAXX_FIELD_NUMBER = 3;
  private double maxX_;
  /**
   * <code>required double maxX = 3;</code>
   */
  public boolean hasMaxX() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required double maxX = 3;</code>
   */
  public double getMaxX() {
    return maxX_;
  }

  // required double minY = 4;
  public static final int MINY_FIELD_NUMBER = 4;
  private double minY_;
  /**
   * <code>required double minY = 4;</code>
   */
  public boolean hasMinY() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>required double minY = 4;</code>
   */
  public double getMinY() {
    return minY_;
  }

  // required double maxY = 5;
  public static final int MAXY_FIELD_NUMBER = 5;
  private double maxY_;
  /**
   * <code>required double maxY = 5;</code>
   */
  public boolean hasMaxY() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>required double maxY = 5;</code>
   */
  public double getMaxY() {
    return maxY_;
  }

  private void initFields() {
    geometry_ = com.google.protobuf.ByteString.EMPTY;
    minX_ = 0D;
    maxX_ = 0D;
    minY_ = 0D;
    maxY_ = 0D;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasGeometry()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasMinX()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasMaxX()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasMinY()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasMaxY()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, geometry_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeDouble(2, minX_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeDouble(3, maxX_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeDouble(4, minY_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeDouble(5, maxY_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, geometry_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, minX_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, maxX_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, minY_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, maxY_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry)) {
      return super.equals(obj);
    }
    gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry other = (gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry) obj;

    boolean result = true;
    result = result && (hasGeometry() == other.hasGeometry());
    if (hasGeometry()) {
      result = result && getGeometry()
          .equals(other.getGeometry());
    }
    result = result && (hasMinX() == other.hasMinX());
    if (hasMinX()) {
      result = result && (Double.doubleToLongBits(getMinX())    == Double.doubleToLongBits(other.getMinX()));
    }
    result = result && (hasMaxX() == other.hasMaxX());
    if (hasMaxX()) {
      result = result && (Double.doubleToLongBits(getMaxX())    == Double.doubleToLongBits(other.getMaxX()));
    }
    result = result && (hasMinY() == other.hasMinY());
    if (hasMinY()) {
      result = result && (Double.doubleToLongBits(getMinY())    == Double.doubleToLongBits(other.getMinY()));
    }
    result = result && (hasMaxY() == other.hasMaxY());
    if (hasMaxY()) {
      result = result && (Double.doubleToLongBits(getMaxY())    == Double.doubleToLongBits(other.getMaxY()));
    }
    result = result &&
        getUnknownFields().equals(other.getUnknownFields());
    return result;
  }

  private int memoizedHashCode = 0;
  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasGeometry()) {
      hash = (37 * hash) + GEOMETRY_FIELD_NUMBER;
      hash = (53 * hash) + getGeometry().hashCode();
    }
    if (hasMinX()) {
      hash = (37 * hash) + MINX_FIELD_NUMBER;
      hash = (53 * hash) + hashLong(
          Double.doubleToLongBits(getMinX()));
    }
    if (hasMaxX()) {
      hash = (37 * hash) + MAXX_FIELD_NUMBER;
      hash = (53 * hash) + hashLong(
          Double.doubleToLongBits(getMaxX()));
    }
    if (hasMinY()) {
      hash = (37 * hash) + MINY_FIELD_NUMBER;
      hash = (53 * hash) + hashLong(
          Double.doubleToLongBits(getMinY()));
    }
    if (hasMaxY()) {
      hash = (37 * hash) + MAXY_FIELD_NUMBER;
      hash = (53 * hash) + hashLong(
          Double.doubleToLongBits(getMaxY()));
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Geometry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements gr.ds.unipi.spatialnodb.messages.proto.geoparquet.GeometryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.ds.unipi.spatialnodb.messages.proto.geoparquet.GeoParquetProtos.internal_static_Geometry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.ds.unipi.spatialnodb.messages.proto.geoparquet.GeoParquetProtos.internal_static_Geometry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry.class, gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry.Builder.class);
    }

    // Construct using gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      geometry_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      minX_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000002);
      maxX_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000004);
      minY_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000008);
      maxY_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gr.ds.unipi.spatialnodb.messages.proto.geoparquet.GeoParquetProtos.internal_static_Geometry_descriptor;
    }

    public gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry getDefaultInstanceForType() {
      return gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry.getDefaultInstance();
    }

    public gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry build() {
      gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry buildPartial() {
      gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry result = new gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.geometry_ = geometry_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.minX_ = minX_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.maxX_ = maxX_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.minY_ = minY_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.maxY_ = maxY_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry) {
        return mergeFrom((gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry other) {
      if (other == gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry.getDefaultInstance()) return this;
      if (other.hasGeometry()) {
        setGeometry(other.getGeometry());
      }
      if (other.hasMinX()) {
        setMinX(other.getMinX());
      }
      if (other.hasMaxX()) {
        setMaxX(other.getMaxX());
      }
      if (other.hasMinY()) {
        setMinY(other.getMinY());
      }
      if (other.hasMaxY()) {
        setMaxY(other.getMaxY());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasGeometry()) {
        
        return false;
      }
      if (!hasMinX()) {
        
        return false;
      }
      if (!hasMaxX()) {
        
        return false;
      }
      if (!hasMinY()) {
        
        return false;
      }
      if (!hasMaxY()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gr.ds.unipi.spatialnodb.messages.proto.geoparquet.Geometry) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required bytes geometry = 1;
    private com.google.protobuf.ByteString geometry_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes geometry = 1;</code>
     */
    public boolean hasGeometry() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes geometry = 1;</code>
     */
    public com.google.protobuf.ByteString getGeometry() {
      return geometry_;
    }
    /**
     * <code>required bytes geometry = 1;</code>
     */
    public Builder setGeometry(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      geometry_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bytes geometry = 1;</code>
     */
    public Builder clearGeometry() {
      bitField0_ = (bitField0_ & ~0x00000001);
      geometry_ = getDefaultInstance().getGeometry();
      onChanged();
      return this;
    }

    // required double minX = 2;
    private double minX_ ;
    /**
     * <code>required double minX = 2;</code>
     */
    public boolean hasMinX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double minX = 2;</code>
     */
    public double getMinX() {
      return minX_;
    }
    /**
     * <code>required double minX = 2;</code>
     */
    public Builder setMinX(double value) {
      bitField0_ |= 0x00000002;
      minX_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required double minX = 2;</code>
     */
    public Builder clearMinX() {
      bitField0_ = (bitField0_ & ~0x00000002);
      minX_ = 0D;
      onChanged();
      return this;
    }

    // required double maxX = 3;
    private double maxX_ ;
    /**
     * <code>required double maxX = 3;</code>
     */
    public boolean hasMaxX() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double maxX = 3;</code>
     */
    public double getMaxX() {
      return maxX_;
    }
    /**
     * <code>required double maxX = 3;</code>
     */
    public Builder setMaxX(double value) {
      bitField0_ |= 0x00000004;
      maxX_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required double maxX = 3;</code>
     */
    public Builder clearMaxX() {
      bitField0_ = (bitField0_ & ~0x00000004);
      maxX_ = 0D;
      onChanged();
      return this;
    }

    // required double minY = 4;
    private double minY_ ;
    /**
     * <code>required double minY = 4;</code>
     */
    public boolean hasMinY() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double minY = 4;</code>
     */
    public double getMinY() {
      return minY_;
    }
    /**
     * <code>required double minY = 4;</code>
     */
    public Builder setMinY(double value) {
      bitField0_ |= 0x00000008;
      minY_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required double minY = 4;</code>
     */
    public Builder clearMinY() {
      bitField0_ = (bitField0_ & ~0x00000008);
      minY_ = 0D;
      onChanged();
      return this;
    }

    // required double maxY = 5;
    private double maxY_ ;
    /**
     * <code>required double maxY = 5;</code>
     */
    public boolean hasMaxY() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required double maxY = 5;</code>
     */
    public double getMaxY() {
      return maxY_;
    }
    /**
     * <code>required double maxY = 5;</code>
     */
    public Builder setMaxY(double value) {
      bitField0_ |= 0x00000010;
      maxY_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required double maxY = 5;</code>
     */
    public Builder clearMaxY() {
      bitField0_ = (bitField0_ & ~0x00000010);
      maxY_ = 0D;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Geometry)
  }

  static {
    defaultInstance = new Geometry(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:Geometry)
}

