// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GeoParquet.proto

package gr.ds.unipi.spatialnodb.messages.proto.geoparquet;

public interface GeometryOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required bytes geometry = 1;
  /**
   * <code>required bytes geometry = 1;</code>
   */
  boolean hasGeometry();
  /**
   * <code>required bytes geometry = 1;</code>
   */
  com.google.protobuf.ByteString getGeometry();

  // required double minX = 2;
  /**
   * <code>required double minX = 2;</code>
   */
  boolean hasMinX();
  /**
   * <code>required double minX = 2;</code>
   */
  double getMinX();

  // required double maxX = 3;
  /**
   * <code>required double maxX = 3;</code>
   */
  boolean hasMaxX();
  /**
   * <code>required double maxX = 3;</code>
   */
  double getMaxX();

  // required double minY = 4;
  /**
   * <code>required double minY = 4;</code>
   */
  boolean hasMinY();
  /**
   * <code>required double minY = 4;</code>
   */
  double getMinY();

  // required double maxY = 5;
  /**
   * <code>required double maxY = 5;</code>
   */
  boolean hasMaxY();
  /**
   * <code>required double maxY = 5;</code>
   */
  double getMaxY();
}
