// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GeoParquet.proto

package gr.ds.unipi.spatialnodb.messages.proto.geoparquet;

public final class GeoParquetProtos {
  private GeoParquetProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Geometry_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Geometry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020GeoParquet.proto\"T\n\010Geometry\022\020\n\010geomet" +
      "ry\030\001 \002(\014\022\014\n\004minX\030\002 \002(\001\022\014\n\004maxX\030\003 \002(\001\022\014\n\004" +
      "minY\030\004 \002(\001\022\014\n\004maxY\030\005 \002(\001B=\n\037gr.ds.unipi." +
      "spatialnodb.parquetB\020GeoParquetProtosH\001P" +
      "\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Geometry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Geometry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Geometry_descriptor,
              new java.lang.String[] { "Geometry", "MinX", "MaxX", "MinY", "MaxY", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
