data-loading {
  rawDataPath="src/main/resources/nari/"
  writePath="src/main/resources/parquet-nari/"
  objectIdIndex=0
  longitudeIndex=1
  latitudeIndex=2
  timeIndex=3
  dateFormat="yyyy-MM-dd HH:mm:ss"
  delimiter=","
;   segK=2
  #Nari
  hilbert {
    bits = 4
;     minLon=-9.713331
;     minLat=45.001045
;     minTime=1443650401000
;     maxLon=-0.015736665
;     maxLat=50.7706
;     maxTime=1459461603000
  }
}
