queries {
  parquetPath="data/parquet-nari-2/"
  queriesFilePath="src/main/resources/trajectory.txt"
  #queriesFilePath="src/main/resources/trajectories.txt"
  pathExport="data/"
  metricsPath="data/"
  epsilon=0.2
  k=5
}
