queries {
  #xLength=0.5
  #yLength=0.5
  #timeLength=86400#seconds
  xLength=0.5
  yLength=0.5
  timeLength=350000#seconds
  numberOfQueries=200
  filePath="src/main/resources/mbb.txt"
  fixedSizes=true
  bounding-box {
            maxLat=50.7705001
            maxLon=-0.015736567
            maxTime=1459461600000
            minLat=45.001045
            minLon=-9.713331
            minTime=1443650401000
  }
}