queries {
  parquetPath="src/main/resources/parquet-nari/"
  queriesFilePath="src/main/resources/queries.txt"
  pathExport="src/main/resources/results.csv"
  metricsPath="src/main/resources/results.csv"

}
