// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpatioTemporal.proto

package gr.ds.unipi.spatialnodb.messages.proto.trajparquet;

public interface SpatioTemporalOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required int32 id = 1;
  /**
   * <code>required int32 id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>required int32 id = 1;</code>
   */
  int getId();

  // required .SpatioTemporal.Coordinates coordinates = 2;
  /**
   * <code>required .SpatioTemporal.Coordinates coordinates = 2;</code>
   */
  boolean hasCoordinates();
  /**
   * <code>required .SpatioTemporal.Coordinates coordinates = 2;</code>
   */
  SpatioTemporal.Coordinates getCoordinates();
  /**
   * <code>required .SpatioTemporal.Coordinates coordinates = 2;</code>
   */
  SpatioTemporal.CoordinatesOrBuilder getCoordinatesOrBuilder();

  // required int64 timestamp = 3;
  /**
   * <code>required int64 timestamp = 3;</code>
   */
  boolean hasTimestamp();
  /**
   * <code>required int64 timestamp = 3;</code>
   */
  long getTimestamp();
}
