// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpatioTemporal.proto

package gr.ds.unipi.spatialnodb.messages.proto.trajparquet;

/**
 * Protobuf type {@code SpatioTemporal}
 */
public  final class SpatioTemporal extends
    com.google.protobuf.GeneratedMessage
    implements SpatioTemporalOrBuilder {
  // Use SpatioTemporal.newBuilder() to construct.
  private SpatioTemporal(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private SpatioTemporal(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final SpatioTemporal defaultInstance;
  public static SpatioTemporal getDefaultInstance() {
    return defaultInstance;
  }

  public SpatioTemporal getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private SpatioTemporal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readInt32();
            break;
          }
          case 18: {
            Coordinates.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = coordinates_.toBuilder();
            }
            coordinates_ = input.readMessage(Coordinates.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(coordinates_);
              coordinates_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            timestamp_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SpatioTemporalProtos.internal_static_SpatioTemporal_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SpatioTemporalProtos.internal_static_SpatioTemporal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SpatioTemporal.class, Builder.class);
  }

  public static com.google.protobuf.Parser<SpatioTemporal> PARSER =
      new com.google.protobuf.AbstractParser<SpatioTemporal>() {
    public SpatioTemporal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SpatioTemporal(input, extensionRegistry);
    }
  };

  @Override
  public com.google.protobuf.Parser<SpatioTemporal> getParserForType() {
    return PARSER;
  }

  public interface CoordinatesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required double longitude = 1;
    /**
     * <code>required double longitude = 1;</code>
     */
    boolean hasLongitude();
    /**
     * <code>required double longitude = 1;</code>
     */
    double getLongitude();

    // required double latitude = 2;
    /**
     * <code>required double latitude = 2;</code>
     */
    boolean hasLatitude();
    /**
     * <code>required double latitude = 2;</code>
     */
    double getLatitude();
  }
  /**
   * Protobuf type {@code SpatioTemporal.Coordinates}
   */
  public static final class Coordinates extends
      com.google.protobuf.GeneratedMessage
      implements CoordinatesOrBuilder {
    // Use Coordinates.newBuilder() to construct.
    private Coordinates(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Coordinates(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Coordinates defaultInstance;
    public static Coordinates getDefaultInstance() {
      return defaultInstance;
    }

    public Coordinates getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Coordinates(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              longitude_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              latitude_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SpatioTemporalProtos.internal_static_SpatioTemporal_Coordinates_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SpatioTemporalProtos.internal_static_SpatioTemporal_Coordinates_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Coordinates.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Coordinates> PARSER =
        new com.google.protobuf.AbstractParser<Coordinates>() {
      public Coordinates parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Coordinates(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Coordinates> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required double longitude = 1;
    public static final int LONGITUDE_FIELD_NUMBER = 1;
    private double longitude_;
    /**
     * <code>required double longitude = 1;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double longitude = 1;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    // required double latitude = 2;
    public static final int LATITUDE_FIELD_NUMBER = 2;
    private double latitude_;
    /**
     * <code>required double latitude = 2;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double latitude = 2;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    private void initFields() {
      longitude_ = 0D;
      latitude_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, longitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, latitude_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, longitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, latitude_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Coordinates)) {
        return super.equals(obj);
      }
      Coordinates other = (Coordinates) obj;

      boolean result = true;
      result = result && (hasLongitude() == other.hasLongitude());
      if (hasLongitude()) {
        result = result && (Double.doubleToLongBits(getLongitude())    == Double.doubleToLongBits(other.getLongitude()));
      }
      result = result && (hasLatitude() == other.hasLatitude());
      if (hasLatitude()) {
        result = result && (Double.doubleToLongBits(getLatitude())    == Double.doubleToLongBits(other.getLatitude()));
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasLongitude()) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getLongitude()));
      }
      if (hasLatitude()) {
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getLatitude()));
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Coordinates parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Coordinates parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Coordinates parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Coordinates parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Coordinates parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Coordinates parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Coordinates parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Coordinates parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Coordinates parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Coordinates parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Coordinates prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SpatioTemporal.Coordinates}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CoordinatesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SpatioTemporalProtos.internal_static_SpatioTemporal_Coordinates_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SpatioTemporalProtos.internal_static_SpatioTemporal_Coordinates_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Coordinates.class, Builder.class);
      }

      // Construct using gr.ds.unipi.spatialnodb.messages.proto.trajparquetold.SpatioTemporal.Coordinates.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SpatioTemporalProtos.internal_static_SpatioTemporal_Coordinates_descriptor;
      }

      public Coordinates getDefaultInstanceForType() {
        return Coordinates.getDefaultInstance();
      }

      public Coordinates build() {
        Coordinates result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Coordinates buildPartial() {
        Coordinates result = new Coordinates(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.latitude_ = latitude_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Coordinates) {
          return mergeFrom((Coordinates)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Coordinates other) {
        if (other == Coordinates.getDefaultInstance()) return this;
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLongitude()) {
          
          return false;
        }
        if (!hasLatitude()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Coordinates parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Coordinates) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required double longitude = 1;
      private double longitude_ ;
      /**
       * <code>required double longitude = 1;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double longitude = 1;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>required double longitude = 1;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000001;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double longitude = 1;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      // required double latitude = 2;
      private double latitude_ ;
      /**
       * <code>required double latitude = 2;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double latitude = 2;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>required double latitude = 2;</code>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000002;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double latitude = 2;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SpatioTemporal.Coordinates)
    }

    static {
      defaultInstance = new Coordinates(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SpatioTemporal.Coordinates)
  }

  private int bitField0_;
  // required int32 id = 1;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>required int32 id = 1;</code>
   */
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  // required .SpatioTemporal.Coordinates coordinates = 2;
  public static final int COORDINATES_FIELD_NUMBER = 2;
  private Coordinates coordinates_;
  /**
   * <code>required .SpatioTemporal.Coordinates coordinates = 2;</code>
   */
  public boolean hasCoordinates() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required .SpatioTemporal.Coordinates coordinates = 2;</code>
   */
  public Coordinates getCoordinates() {
    return coordinates_;
  }
  /**
   * <code>required .SpatioTemporal.Coordinates coordinates = 2;</code>
   */
  public CoordinatesOrBuilder getCoordinatesOrBuilder() {
    return coordinates_;
  }

  // required int64 timestamp = 3;
  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private long timestamp_;
  /**
   * <code>required int64 timestamp = 3;</code>
   */
  public boolean hasTimestamp() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required int64 timestamp = 3;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  private void initFields() {
    id_ = 0;
    coordinates_ = Coordinates.getDefaultInstance();
    timestamp_ = 0L;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasCoordinates()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasTimestamp()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getCoordinates().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, coordinates_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt64(3, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, coordinates_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  protected Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SpatioTemporal)) {
      return super.equals(obj);
    }
    SpatioTemporal other = (SpatioTemporal) obj;

    boolean result = true;
    result = result && (hasId() == other.hasId());
    if (hasId()) {
      result = result && (getId()
          == other.getId());
    }
    result = result && (hasCoordinates() == other.hasCoordinates());
    if (hasCoordinates()) {
      result = result && getCoordinates()
          .equals(other.getCoordinates());
    }
    result = result && (hasTimestamp() == other.hasTimestamp());
    if (hasTimestamp()) {
      result = result && (getTimestamp()
          == other.getTimestamp());
    }
    result = result &&
        getUnknownFields().equals(other.getUnknownFields());
    return result;
  }

  private int memoizedHashCode = 0;
  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
    }
    if (hasCoordinates()) {
      hash = (37 * hash) + COORDINATES_FIELD_NUMBER;
      hash = (53 * hash) + getCoordinates().hashCode();
    }
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + hashLong(getTimestamp());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SpatioTemporal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpatioTemporal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpatioTemporal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpatioTemporal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpatioTemporal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static SpatioTemporal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static SpatioTemporal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static SpatioTemporal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static SpatioTemporal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static SpatioTemporal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(SpatioTemporal prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SpatioTemporal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements SpatioTemporalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SpatioTemporalProtos.internal_static_SpatioTemporal_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SpatioTemporalProtos.internal_static_SpatioTemporal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SpatioTemporal.class, Builder.class);
    }

    // Construct using gr.ds.unipi.spatialnodb.messages.proto.trajparquetold.SpatioTemporal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getCoordinatesFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      id_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (coordinatesBuilder_ == null) {
        coordinates_ = Coordinates.getDefaultInstance();
      } else {
        coordinatesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      timestamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SpatioTemporalProtos.internal_static_SpatioTemporal_descriptor;
    }

    public SpatioTemporal getDefaultInstanceForType() {
      return SpatioTemporal.getDefaultInstance();
    }

    public SpatioTemporal build() {
      SpatioTemporal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public SpatioTemporal buildPartial() {
      SpatioTemporal result = new SpatioTemporal(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.id_ = id_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (coordinatesBuilder_ == null) {
        result.coordinates_ = coordinates_;
      } else {
        result.coordinates_ = coordinatesBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.timestamp_ = timestamp_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SpatioTemporal) {
        return mergeFrom((SpatioTemporal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SpatioTemporal other) {
      if (other == SpatioTemporal.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasCoordinates()) {
        mergeCoordinates(other.getCoordinates());
      }
      if (other.hasTimestamp()) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasId()) {
        
        return false;
      }
      if (!hasCoordinates()) {
        
        return false;
      }
      if (!hasTimestamp()) {
        
        return false;
      }
      if (!getCoordinates().isInitialized()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SpatioTemporal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SpatioTemporal) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required int32 id = 1;
    private int id_ ;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public Builder setId(int value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    // required .SpatioTemporal.Coordinates coordinates = 2;
    private Coordinates coordinates_ = Coordinates.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        Coordinates, Coordinates.Builder, CoordinatesOrBuilder> coordinatesBuilder_;
    /**
     * <code>required .SpatioTemporal.Coordinates coordinates = 2;</code>
     */
    public boolean hasCoordinates() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .SpatioTemporal.Coordinates coordinates = 2;</code>
     */
    public Coordinates getCoordinates() {
      if (coordinatesBuilder_ == null) {
        return coordinates_;
      } else {
        return coordinatesBuilder_.getMessage();
      }
    }
    /**
     * <code>required .SpatioTemporal.Coordinates coordinates = 2;</code>
     */
    public Builder setCoordinates(Coordinates value) {
      if (coordinatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        coordinates_ = value;
        onChanged();
      } else {
        coordinatesBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .SpatioTemporal.Coordinates coordinates = 2;</code>
     */
    public Builder setCoordinates(
        Coordinates.Builder builderForValue) {
      if (coordinatesBuilder_ == null) {
        coordinates_ = builderForValue.build();
        onChanged();
      } else {
        coordinatesBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .SpatioTemporal.Coordinates coordinates = 2;</code>
     */
    public Builder mergeCoordinates(Coordinates value) {
      if (coordinatesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            coordinates_ != Coordinates.getDefaultInstance()) {
          coordinates_ =
            Coordinates.newBuilder(coordinates_).mergeFrom(value).buildPartial();
        } else {
          coordinates_ = value;
        }
        onChanged();
      } else {
        coordinatesBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .SpatioTemporal.Coordinates coordinates = 2;</code>
     */
    public Builder clearCoordinates() {
      if (coordinatesBuilder_ == null) {
        coordinates_ = Coordinates.getDefaultInstance();
        onChanged();
      } else {
        coordinatesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>required .SpatioTemporal.Coordinates coordinates = 2;</code>
     */
    public Coordinates.Builder getCoordinatesBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getCoordinatesFieldBuilder().getBuilder();
    }
    /**
     * <code>required .SpatioTemporal.Coordinates coordinates = 2;</code>
     */
    public CoordinatesOrBuilder getCoordinatesOrBuilder() {
      if (coordinatesBuilder_ != null) {
        return coordinatesBuilder_.getMessageOrBuilder();
      } else {
        return coordinates_;
      }
    }
    /**
     * <code>required .SpatioTemporal.Coordinates coordinates = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        Coordinates, Coordinates.Builder, CoordinatesOrBuilder>
        getCoordinatesFieldBuilder() {
      if (coordinatesBuilder_ == null) {
        coordinatesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            Coordinates, Coordinates.Builder, CoordinatesOrBuilder>(
                coordinates_,
                getParentForChildren(),
                isClean());
        coordinates_ = null;
      }
      return coordinatesBuilder_;
    }

    // required int64 timestamp = 3;
    private long timestamp_ ;
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    public Builder setTimestamp(long value) {
      bitField0_ |= 0x00000004;
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000004);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:SpatioTemporal)
  }

  static {
    defaultInstance = new SpatioTemporal(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:SpatioTemporal)
}

