// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpatioTemporal.proto

package gr.ds.unipi.spatialnodb.messages.proto.trajparquet;

public final class SpatioTemporalProtos {
  private SpatioTemporalProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_SpatioTemporal_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SpatioTemporal_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_SpatioTemporal_Coordinates_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SpatioTemporal_Coordinates_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024SpatioTemporal.proto\"\225\001\n\016SpatioTempora" +
      "l\022\n\n\002id\030\001 \002(\005\0220\n\013coordinates\030\002 \002(\0132\033.Spa" +
      "tioTemporal.Coordinates\022\021\n\ttimestamp\030\003 \002" +
      "(\003\0322\n\013Coordinates\022\021\n\tlongitude\030\001 \002(\001\022\020\n\010" +
      "latitude\030\002 \002(\001BA\n\037gr.ds.unipi.spatialnod" +
      "b.parquetB\024SpatioTemporalProtosH\001P\001\210\001\001\240\001" +
      "\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SpatioTemporal_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SpatioTemporal_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SpatioTemporal_descriptor,
              new String[] { "Id", "Coordinates", "Timestamp", });
          internal_static_SpatioTemporal_Coordinates_descriptor =
            internal_static_SpatioTemporal_descriptor.getNestedTypes().get(0);
          internal_static_SpatioTemporal_Coordinates_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SpatioTemporal_Coordinates_descriptor,
              new String[] { "Longitude", "Latitude", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
