// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpatioTemporalPoints.proto

package gr.ds.unipi.spatialnodb.messages.common.segmentv2;

public interface SpatioTemporalPointsOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;
  /**
   * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
   */
  java.util.List<gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint> 
      getSptList();
  /**
   * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
   */
  gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint getSpt(int index);
  /**
   * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
   */
  int getSptCount();
  /**
   * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
   */
  java.util.List<? extends gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPointOrBuilder> 
      getSptOrBuilderList();
  /**
   * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
   */
  gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPointOrBuilder getSptOrBuilder(
      int index);
}
