// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpatioTemporalPoints.proto

package gr.ds.unipi.spatialnodb.messages.common.segmentv2;

public final class SpatioTemporalPointsProtos {
  private SpatioTemporalPointsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_SpatioTemporalPoints_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SpatioTemporalPoints_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_SpatioTemporalPoints_SpatioTemporalPoint_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SpatioTemporalPoints_SpatioTemporalPoint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032SpatioTemporalPoints.proto\"\235\001\n\024SpatioT" +
      "emporalPoints\0226\n\003spt\030\001 \003(\0132).SpatioTempo" +
      "ralPoints.SpatioTemporalPoint\032M\n\023SpatioT" +
      "emporalPoint\022\021\n\tlongitude\030\001 \002(\001\022\020\n\010latit" +
      "ude\030\002 \002(\001\022\021\n\ttimestamp\030\003 \002(\003BG\n\037gr.ds.un" +
      "ipi.spatialnodb.parquetB\032SpatioTemporalP" +
      "ointsProtosH\001P\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SpatioTemporalPoints_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SpatioTemporalPoints_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SpatioTemporalPoints_descriptor,
              new String[] { "Spt", });
          internal_static_SpatioTemporalPoints_SpatioTemporalPoint_descriptor =
            internal_static_SpatioTemporalPoints_descriptor.getNestedTypes().get(0);
          internal_static_SpatioTemporalPoints_SpatioTemporalPoint_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SpatioTemporalPoints_SpatioTemporalPoint_descriptor,
              new String[] { "Longitude", "Latitude", "Timestamp", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
