// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpatioTemporalPoints.proto

package gr.ds.unipi.spatialnodb.messages.common.segmentv2;

/**
 * Protobuf type {@code SpatioTemporalPoints}
 */
public  final class SpatioTemporalPoints extends
    com.google.protobuf.GeneratedMessage
    implements SpatioTemporalPointsOrBuilder {
  // Use SpatioTemporalPoints.newBuilder() to construct.
  private SpatioTemporalPoints(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private SpatioTemporalPoints(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final SpatioTemporalPoints defaultInstance;
  public static SpatioTemporalPoints getDefaultInstance() {
    return defaultInstance;
  }

  public SpatioTemporalPoints getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private SpatioTemporalPoints(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              spt_ = new java.util.ArrayList<gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint>();
              mutable_bitField0_ |= 0x00000001;
            }
            spt_.add(input.readMessage(gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        spt_ = java.util.Collections.unmodifiableList(spt_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPointsProtos.internal_static_SpatioTemporalPoints_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPointsProtos.internal_static_SpatioTemporalPoints_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.class, gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.Builder.class);
  }

  public static com.google.protobuf.Parser<SpatioTemporalPoints> PARSER =
      new com.google.protobuf.AbstractParser<SpatioTemporalPoints>() {
    public SpatioTemporalPoints parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SpatioTemporalPoints(input, extensionRegistry);
    }
  };

  @Override
  public com.google.protobuf.Parser<SpatioTemporalPoints> getParserForType() {
    return PARSER;
  }

  public interface SpatioTemporalPointOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required double longitude = 1;
    /**
     * <code>required double longitude = 1;</code>
     */
    boolean hasLongitude();
    /**
     * <code>required double longitude = 1;</code>
     */
    double getLongitude();

    // required double latitude = 2;
    /**
     * <code>required double latitude = 2;</code>
     */
    boolean hasLatitude();
    /**
     * <code>required double latitude = 2;</code>
     */
    double getLatitude();

    // required int64 timestamp = 3;
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code SpatioTemporalPoints.SpatioTemporalPoint}
   */
  public static final class SpatioTemporalPoint extends
      com.google.protobuf.GeneratedMessage
      implements SpatioTemporalPointOrBuilder {
    // Use SpatioTemporalPoint.newBuilder() to construct.
    private SpatioTemporalPoint(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SpatioTemporalPoint(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SpatioTemporalPoint defaultInstance;
    public static SpatioTemporalPoint getDefaultInstance() {
      return defaultInstance;
    }

    public SpatioTemporalPoint getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SpatioTemporalPoint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              longitude_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              latitude_ = input.readDouble();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPointsProtos.internal_static_SpatioTemporalPoints_SpatioTemporalPoint_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPointsProtos.internal_static_SpatioTemporalPoints_SpatioTemporalPoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.class, gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.Builder.class);
    }

    public static com.google.protobuf.Parser<SpatioTemporalPoint> PARSER =
        new com.google.protobuf.AbstractParser<SpatioTemporalPoint>() {
      public SpatioTemporalPoint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SpatioTemporalPoint(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<SpatioTemporalPoint> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required double longitude = 1;
    public static final int LONGITUDE_FIELD_NUMBER = 1;
    private double longitude_;
    /**
     * <code>required double longitude = 1;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double longitude = 1;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    // required double latitude = 2;
    public static final int LATITUDE_FIELD_NUMBER = 2;
    private double latitude_;
    /**
     * <code>required double latitude = 2;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double latitude = 2;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    // required int64 timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      longitude_ = 0D;
      latitude_ = 0D;
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, longitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, latitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, longitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, latitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint)) {
        return super.equals(obj);
      }
      gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint other = (gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint) obj;

      boolean result = true;
      result = result && (hasLongitude() == other.hasLongitude());
      if (hasLongitude()) {
        result = result && (Double.doubleToLongBits(getLongitude())    == Double.doubleToLongBits(other.getLongitude()));
      }
      result = result && (hasLatitude() == other.hasLatitude());
      if (hasLatitude()) {
        result = result && (Double.doubleToLongBits(getLatitude())    == Double.doubleToLongBits(other.getLatitude()));
      }
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasLongitude()) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getLongitude()));
      }
      if (hasLatitude()) {
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getLatitude()));
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getTimestamp());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SpatioTemporalPoints.SpatioTemporalPoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPointsProtos.internal_static_SpatioTemporalPoints_SpatioTemporalPoint_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPointsProtos.internal_static_SpatioTemporalPoints_SpatioTemporalPoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.class, gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.Builder.class);
      }

      // Construct using gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPointsProtos.internal_static_SpatioTemporalPoints_SpatioTemporalPoint_descriptor;
      }

      public gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint getDefaultInstanceForType() {
        return gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.getDefaultInstance();
      }

      public gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint build() {
        gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint buildPartial() {
        gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint result = new gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint) {
          return mergeFrom((gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint other) {
        if (other == gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.getDefaultInstance()) return this;
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLongitude()) {
          
          return false;
        }
        if (!hasLatitude()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required double longitude = 1;
      private double longitude_ ;
      /**
       * <code>required double longitude = 1;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double longitude = 1;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>required double longitude = 1;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000001;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double longitude = 1;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      // required double latitude = 2;
      private double latitude_ ;
      /**
       * <code>required double latitude = 2;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double latitude = 2;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>required double latitude = 2;</code>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000002;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double latitude = 2;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      // required int64 timestamp = 3;
      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SpatioTemporalPoints.SpatioTemporalPoint)
    }

    static {
      defaultInstance = new SpatioTemporalPoint(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SpatioTemporalPoints.SpatioTemporalPoint)
  }

  // repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;
  public static final int SPT_FIELD_NUMBER = 1;
  private java.util.List<gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint> spt_;
  /**
   * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
   */
  public java.util.List<gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint> getSptList() {
    return spt_;
  }
  /**
   * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
   */
  public java.util.List<? extends gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPointOrBuilder> 
      getSptOrBuilderList() {
    return spt_;
  }
  /**
   * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
   */
  public int getSptCount() {
    return spt_.size();
  }
  /**
   * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
   */
  public gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint getSpt(int index) {
    return spt_.get(index);
  }
  /**
   * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
   */
  public gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPointOrBuilder getSptOrBuilder(
      int index) {
    return spt_.get(index);
  }

  private void initFields() {
    spt_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    for (int i = 0; i < getSptCount(); i++) {
      if (!getSpt(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < spt_.size(); i++) {
      output.writeMessage(1, spt_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < spt_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, spt_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  protected Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints)) {
      return super.equals(obj);
    }
    gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints other = (gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints) obj;

    boolean result = true;
    result = result && getSptList()
        .equals(other.getSptList());
    result = result &&
        getUnknownFields().equals(other.getUnknownFields());
    return result;
  }

  private int memoizedHashCode = 0;
  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getSptCount() > 0) {
      hash = (37 * hash) + SPT_FIELD_NUMBER;
      hash = (53 * hash) + getSptList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SpatioTemporalPoints}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPointsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPointsProtos.internal_static_SpatioTemporalPoints_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPointsProtos.internal_static_SpatioTemporalPoints_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.class, gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.Builder.class);
    }

    // Construct using gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getSptFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (sptBuilder_ == null) {
        spt_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        sptBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPointsProtos.internal_static_SpatioTemporalPoints_descriptor;
    }

    public gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints getDefaultInstanceForType() {
      return gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.getDefaultInstance();
    }

    public gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints build() {
      gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints buildPartial() {
      gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints result = new gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints(this);
      int from_bitField0_ = bitField0_;
      if (sptBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          spt_ = java.util.Collections.unmodifiableList(spt_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.spt_ = spt_;
      } else {
        result.spt_ = sptBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints) {
        return mergeFrom((gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints other) {
      if (other == gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.getDefaultInstance()) return this;
      if (sptBuilder_ == null) {
        if (!other.spt_.isEmpty()) {
          if (spt_.isEmpty()) {
            spt_ = other.spt_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSptIsMutable();
            spt_.addAll(other.spt_);
          }
          onChanged();
        }
      } else {
        if (!other.spt_.isEmpty()) {
          if (sptBuilder_.isEmpty()) {
            sptBuilder_.dispose();
            sptBuilder_ = null;
            spt_ = other.spt_;
            bitField0_ = (bitField0_ & ~0x00000001);
            sptBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getSptFieldBuilder() : null;
          } else {
            sptBuilder_.addAllMessages(other.spt_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      for (int i = 0; i < getSptCount(); i++) {
        if (!getSpt(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;
    private java.util.List<gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint> spt_ =
      java.util.Collections.emptyList();
    private void ensureSptIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        spt_ = new java.util.ArrayList<gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint>(spt_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint, gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.Builder, gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPointOrBuilder> sptBuilder_;

    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public java.util.List<gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint> getSptList() {
      if (sptBuilder_ == null) {
        return java.util.Collections.unmodifiableList(spt_);
      } else {
        return sptBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public int getSptCount() {
      if (sptBuilder_ == null) {
        return spt_.size();
      } else {
        return sptBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint getSpt(int index) {
      if (sptBuilder_ == null) {
        return spt_.get(index);
      } else {
        return sptBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public Builder setSpt(
        int index, gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint value) {
      if (sptBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSptIsMutable();
        spt_.set(index, value);
        onChanged();
      } else {
        sptBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public Builder setSpt(
        int index, gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.Builder builderForValue) {
      if (sptBuilder_ == null) {
        ensureSptIsMutable();
        spt_.set(index, builderForValue.build());
        onChanged();
      } else {
        sptBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public Builder addSpt(gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint value) {
      if (sptBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSptIsMutable();
        spt_.add(value);
        onChanged();
      } else {
        sptBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public Builder addSpt(
        int index, gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint value) {
      if (sptBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSptIsMutable();
        spt_.add(index, value);
        onChanged();
      } else {
        sptBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public Builder addSpt(
        gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.Builder builderForValue) {
      if (sptBuilder_ == null) {
        ensureSptIsMutable();
        spt_.add(builderForValue.build());
        onChanged();
      } else {
        sptBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public Builder addSpt(
        int index, gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.Builder builderForValue) {
      if (sptBuilder_ == null) {
        ensureSptIsMutable();
        spt_.add(index, builderForValue.build());
        onChanged();
      } else {
        sptBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public Builder addAllSpt(
        Iterable<? extends gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint> values) {
      if (sptBuilder_ == null) {
        ensureSptIsMutable();
        super.addAll(values, spt_);
        onChanged();
      } else {
        sptBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public Builder clearSpt() {
      if (sptBuilder_ == null) {
        spt_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        sptBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public Builder removeSpt(int index) {
      if (sptBuilder_ == null) {
        ensureSptIsMutable();
        spt_.remove(index);
        onChanged();
      } else {
        sptBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.Builder getSptBuilder(
        int index) {
      return getSptFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPointOrBuilder getSptOrBuilder(
        int index) {
      if (sptBuilder_ == null) {
        return spt_.get(index);  } else {
        return sptBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public java.util.List<? extends gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPointOrBuilder> 
         getSptOrBuilderList() {
      if (sptBuilder_ != null) {
        return sptBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(spt_);
      }
    }
    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.Builder addSptBuilder() {
      return getSptFieldBuilder().addBuilder(
          gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.getDefaultInstance());
    }
    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.Builder addSptBuilder(
        int index) {
      return getSptFieldBuilder().addBuilder(
          index, gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.getDefaultInstance());
    }
    /**
     * <code>repeated .SpatioTemporalPoints.SpatioTemporalPoint spt = 1;</code>
     */
    public java.util.List<gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.Builder> 
         getSptBuilderList() {
      return getSptFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint, gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.Builder, gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPointOrBuilder> 
        getSptFieldBuilder() {
      if (sptBuilder_ == null) {
        sptBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint, gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPoint.Builder, gr.ds.unipi.spatialnodb.messages.common.segmentv2.SpatioTemporalPoints.SpatioTemporalPointOrBuilder>(
                spt_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        spt_ = null;
      }
      return sptBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:SpatioTemporalPoints)
  }

  static {
    defaultInstance = new SpatioTemporalPoints(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:SpatioTemporalPoints)
}

